-- Argo
CREATE ROLE ${ARGO_POSTGRESQL_USER} WITH LOGIN PASSWORD '${ARGO_POSTGRESQL_PASSWORD}';
CREATE DATABASE ${ARGO_DATABSE} WITH OWNER ${ARGO_POSTGRESQL_USER};

-- Cosmotech API
CREATE ROLE ${COSMOTECH_API_READER_USER} WITH LOGIN PASSWORD '${COSMOTECH_API_READER_PASSWORD}';
CREATE ROLE ${COSMOTECH_API_ADMIN_USER} WITH LOGIN PASSWORD '${COSMOTECH_API_ADMIN_PASSWORD}' CREATEDB;
